# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/rerost/information-retrieval-tools-go
    steps:
      - checkout
      - run: go get github.com/direnv/direnv
      - run: eval "$(direnv hook bash)"
      - run: direnv allow
      - run: make vendor
      - run: make test
      # - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
